### ISSUE TITLE
LDAP search (ocflib.account.search) doesn't escape searches properly

### ISSUE THREAD

**Issue by jvperrin** [ocf/ocflib#150]
This causes errors like this, when a search contains parentheses:

```
Traceback (most recent call last):
  File "/opt/ocfweb/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ocfweb/ocfweb/account/register.py", line 122, in recommend
    recommendations = recommender.recommend(real_name, 10)
  File "/opt/ocfweb/ocfweb/account/recommender.py", line 30, in recommend
    validate_username(rec, real_name)
  File "/opt/ocfweb/venv/lib/python3.5/site-packages/ocflib/account/creation.py", line 328, in validate_username
    if search.user_exists(username):
  File "/opt/ocfweb/venv/lib/python3.5/site-packages/ocflib/account/search.py", line 61, in user_exists
    return bool(user_attrs(account))
  File "/opt/ocfweb/venv/lib/python3.5/site-packages/ocflib/account/search.py", line 48, in user_attrs
    c.search(base, '(uid={})'.format(uid), attributes=ldap3.ALL_ATTRIBUTES)
  File "/opt/ocfweb/venv/lib/python3.5/site-packages/ldap3/core/connection.py", line 779, in search
    check_names=self.check_names)
  File "/opt/ocfweb/venv/lib/python3.5/site-packages/ldap3/operation/search.py", line 372, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode, validator, check_names).elements[0])  # parse the searchFilter string and compile it starting from the root node
  File "/opt/ocfweb/venv/lib/python3.5/site-packages/ldap3/operation/search.py", line 220, in parse_filter
    raise LDAPInvalidFilterError('invalid filter')
ldap3.core.exceptions.LDAPInvalidFilterError: invalid filter



Request:
  * Host: www.ocf.berkeley.edu
  * Path: /account/register/recommend/?real_name=Xiao%20(Calvin)%20Hu
  * Method: GET
  * Secure: True
```

We might be able to use `escape_bytes` from `ldap3` or maybe just escape parentheses and move on since we quite rarely encounter this issue.

**Comment by kpengboy** [comment]
> or maybe just escape parentheses and move on
Well there was also that person whose name had a * in it once. We really should use `escape_bytes`...

**Comment by kpengboy** [comment]
Heck, we might want to audit the entire codebase for potential LDAP injection attack vectors...
