### ISSUE TITLE
Error in check script

### ISSUE THREAD

**Issue by BernardZhao** [ocf/ocflib#191]
I ran `check ith`, and got the following error:

```
bernardzhao@invasion:~$ check ith
\ith:*:60147:1000:Thee Ho:/home/i/it/ith:/bin/bash
Created on: 2019-05-01
Member of group(s): ocf ocfstaff
CalNet UID number: 1662297

ith printing quota:
  → 196 remaining this semester
  → 20 remaining today

Signatories/Signatory for:
Traceback (most recent call last):
  File "/opt/share/utils/sbin/signat", line 212, in <module>
    main()
  File "/opt/share/utils/sbin/signat", line 204, in main
    show_by_username(args.username)
  File "/opt/share/utils/sbin/signat", line 49, in show_by_username
    show_groups_by_student_signat(uid)
  File "/opt/share/utils/sbin/signat", line 88, in show_groups_by_student_signat
    name = directory.name_by_calnet_uid(uid)
  File "/usr/lib/python3/dist-packages/ocflib/ucb/directory.py", line 20, in name_by_calnet_uid
    names = get_calnet_names(uid)
  File "/usr/lib/python3/dist-packages/ocflib/ucb/directory.py", line 9, in get_calnet_names
    attrs = search.user_attrs_ucb(uid)
  File "/usr/lib/python3/dist-packages/ocflib/account/search.py", line 65, in user_attrs_ucb
    base=UCB_LDAP_PEOPLE)
  File "/usr/lib/python3/dist-packages/ocflib/account/search.py", line 55, in user_attrs
    '(uid={})'.format(escape_filter_chars(uid)),
  File "/usr/lib/python3/dist-packages/ldap3/utils/conv.py", line 36, in escape_filter_chars
    output = text.replace('\\', r'\5c')
AttributeError: 'list' object has no attribute 'replace'
```

**Comment by ja5087** [comment]
See https://github.com/ocf/utils/issues/128#issuecomment-533725081

**Comment by BernardZhao** [comment]
Thanks @ja5087
